language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv python-numpy python-minimal python-mock python-pam python-pil python-nose python-glade2 python-matplotlib
 - sudo dpkg -L python-opencv
 
# command to run tests
script: unittests