language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install python-opencv python-numpy python-minimal python-mock python-pam python-pil python-nose python-glade2 python-matplotlib python-sklearn python-tk python-twisted-core python-sklearn-lib -qq
 - sudo dpkg -L python-opencv
 
# command to run tests
script: unittests